"""empty message

Revision ID: c6e2883677ee
Revises: 
Create Date: 2021-03-14 13:55:30.323384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6e2883677ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount >= 0', name='check1'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='accounts_user_id')
    )
    op.create_table('operation_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', postgresql.UUID(), nullable=True),
    sa.Column('destination', postgresql.UUID(), nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['destination'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_history_destination'), 'operation_history', ['destination'], unique=False)
    op.create_index(op.f('ix_operation_history_source'), 'operation_history', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_history_source'), table_name='operation_history')
    op.drop_index(op.f('ix_operation_history_destination'), table_name='operation_history')
    op.drop_table('operation_history')
    op.drop_table('accounts')
    # ### end Alembic commands ###
